#ifndef INTERFACEBUILDER_H_INCLUDED
#define INTERFACEBUILDER_H_INCLUDED

const POINT WINDOW_SIZE = {800, 600};
const COLORREF WINDOW_COLOR = RGB (212, 208, 200);

#include "Page1.h"

#endif // INTERFACEBUILDER_H_INCLUDED
